spring.application.name=csvsync

logging.level.com.esomos.csvsync.service.DataBaseService=DEBUG
logging.level.org.springframework=INFO

spring.jvm.options=-Xms512m -Xmx5120m



# PostgreSQL MNTO Data Base settings
spring.datasource.url=jdbc:postgresql://localhost:5433/postgres
spring.datasource.username=mnto
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.port=5433
